name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Agrega tu nombre de usuario de Docker Hub como secreto en GitHub
          password: ${{ secrets.DOCKER_PASSWORD }}  # Agrega tu contraseña de Docker Hub como secreto en GitHub

      - name: Build the Docker image
        run: |
          docker build . -t taskuser/task-management-app:${{ github.sha }}  # Reemplaza con tu nombre de usuario y nombre de la aplicación

      - name: Push the Docker image
        run: |
          docker push taskuser/task-management-app:${{ github.sha }}  # Reemplaza con tu nombre de usuario y nombre de la aplicación
